# Generated by Django 5.2.4 on 2025-08-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(help_text="e.g., 'Computer Science', 'Data Analysis'", max_length=255)),
                ('bio', models.TextField(blank=True, help_text='A brief biography of the expert.')),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
