# Generated by Django 5.2.4 on 2026-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='avg_communication',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='avg_rubric_adherence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='avg_timeliness',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='recommendation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of reviewers who would recommend this expert.', max_digits=5),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='stripe_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='field_of_study',
            field=models.CharField(max_length=255),
        ),
    ]
