# Generated by Django 5.2.4 on 2026-05-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_profiles', '0003_expertprofile_avg_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
