# Generated by Django 5.2.4 on 2026-05-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_profiles', '0004_expertprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='stripe_account_verified',
        ),
    ]
