# Generated by Django 5.2.4 on 2026-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('expert', 'Expert'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
