# Generated by Django 5.2.4 on 2026-04-23 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation_pair',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_1', 'participant_2')},
        ),
    ]
