# Generated by Django 5.2.4 on 2025-08-01 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('expert_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentbid',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentbid',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='expert_profiles.expertprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentbid',
            unique_together={('assignment', 'expert')},
        ),
    ]
