# Generated by Django 5.2.4 on 2026-04-23 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_profiles', '0003_expertprofile_avg_communication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gigs.academiccategory')),
            ],
            options={
                'verbose_name_plural': 'Academic Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('cover_image', models.URLField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('requirements_prompt', models.TextField(blank=True, help_text='Questions the student must answer before work begins (e.g. citation style, word count, rubric upload).')),
                ('sales', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='gigs.academiccategory')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='expert_profiles.expertprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GigExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '24-hour turnaround'", max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_days', models.PositiveSmallIntegerField(default=0, help_text='Additional delivery days this extra adds.')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='gigs.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('name', models.CharField(help_text="e.g. 'Literature Review'", max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveSmallIntegerField()),
                ('revision_number', models.PositiveSmallIntegerField(default=1)),
                ('features', models.JSONField(default=list, help_text='List of included features')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gigs.gig')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('gig', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=200)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extras', models.ManyToManyField(blank=True, to='gigs.gigextra')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gigs.gigpackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_style', models.CharField(blank=True, choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Chicago', 'Chicago'), ('Harvard', 'Harvard'), ('Other', 'Other')], max_length=20)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rubric_file', models.FileField(blank=True, null=True, upload_to='orders/rubrics/')),
                ('additional_notes', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict, help_text="Free-form answers to the gig's requirements_prompt questions.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='gigs.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_adherence_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('comment', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='expert_profiles.expertprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='gigs.order')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
