# Generated by Django 5.2.4 on 2026-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
