# Generated by Django 5.2.4 on 2026-05-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_fee_percent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_transfer_id',
        ),
    ]
