# Generated by Django 5.2.4 on 2026-05-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_remove_order_platform_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gigs.gigpackage'),
        ),
    ]
