# Generated by Django 5.2.4 on 2026-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_order_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Admin-pinned gigs are surfaced at the top of listings.'),
        ),
        migrations.AddField(
            model_name='gig',
            name='pinned_at',
            field=models.DateTimeField(blank=True, help_text='When this gig was pinned. Cleared when unpinned.', null=True),
        ),
    ]
